### ISSUE TITLE
Travis CI badge URLs point to travis-ci.org

### ISSUE THREAD

**Issue by onebytegone** [silvermine/generator-typescript#10]
Both the [project README](https://github.com/silvermine/generator-typescript/blame/d5d3e5ba67bb912681277fd7cad8bc662165bda9/README.md#L3-L4) and the [README template](https://github.com/silvermine/generator-typescript/blame/d5d3e5ba67bb912681277fd7cad8bc662165bda9/generators/app/templates/README.md#L4-L5) point to travis-ci.org badges instead of the newer travis-ci.com. Since this project is running on travis-ci.com, shouldn't it be using those badges? Also, do we want this generator to create new projects that are pointing to travis-ci.com?

**Comment by jthomerson** [comment]
Good catch. Yes, we need to update this project and its templates. @yokuze @onebytegone PR welcome.
