### ISSUE TITLE
Consider adding commit message linting and CHANGELOG generation

### ISSUE THREAD

**Issue by yokuze** [silvermine/generator-typescript#33]
Commit message linting and CHANGELOG generation was [added to the lambda-express project](https://github.com/silvermine/lambda-express/pull/15). This will serve as an acceptance test for the Silvermine team. If we choose to adopt these standards, we should consider adding the configuration to this generator.

**Comment by jthomerson** [comment]
We have adopted these standards.

As part of this issue, we should make sure that a generated project properly creates CHANGELOG files, and the URLs in the CHANGELOG are correct (for commits, issues, and compares).

**Comment by yokuze** [comment]
Added in #36
