### ISSUE TITLE
Add `--forbid-only` to CI tests

### ISSUE THREAD

**Issue by jthomerson** [silvermine/generator-typescript#40]
Developers commonly add `.only` to their tests (e.g. `describe.only('some class')` or `it.only('...')`) to speed up their development process. Occasionally those accidentally slip into a commit. If they go into a commit, we should see a drastic drop in code coverage, but other than that, there's nothing to prevent the test suite from being effectively neutered.

If we added [`--forbid-only`](https://mochajs.org/#-forbid-only) to the Mocha config used by the CI builds, the tests would fail if someone accidentally committed one.

Note that we probably don't want to just add it to `.mocha.opts` because then `npm test` won't work for the developer with `.only`.

**Comment by yokuze** [comment]
This was fixed with #42 and can be closed.
